export OPENSTACK_CLOUD=openstack
export OPENSTACK_CLOUD_YAML_B64=Y2xvdWRzOgogIG9wZW5zdGFjazoKICAgIGF1dGg6CiAgICAgIGF1dGhfdXJsOiBodHRwOi8vMTkyLjE2OC43Ny4xMS9pZGVudGl0eQogICAgICB1c2VybmFtZTogInN1bm1pIgogICAgICBwYXNzd29yZDogImZrZmZrNDQ4IgogICAgICBwcm9qZWN0X2lkOiA1NDJlN2EwNGY2OTE0ODI5YjQzZTc3ZjllZjEyYjc3OQogICAgICBwcm9qZWN0X25hbWU6ICJlZGdlY3JhZnQiCiAgICAgIHVzZXJfZG9tYWluX25hbWU6ICJEZWZhdWx0IgogICAgcmVnaW9uX25hbWU6ICJSZWdpb25PbmUiCiAgICBpbnRlcmZhY2U6ICJwdWJsaWMiCiAgICBpZGVudGl0eV9hcGlfdmVyc2lvbjogMwo=
export OPENSTACK_CLOUD_PROVIDER_CONF_B64=W0dsb2JhbF0KYXV0aC11cmw9aHR0cDovLzE5Mi4xNjguNzcuMTEvaWRlbnRpdHkKdXNlcm5hbWU9InN1bm1pIgpwYXNzd29yZD0iZmtmZms0NDgiCnRlbmFudC1pZD0iNTQyZTdhMDRmNjkxNDgyOWI0M2U3N2Y5ZWYxMmI3NzkiCnRlbmFudC1uYW1lPSJlZGdlY3JhZnQiCmRvbWFpbi1uYW1lPSJEZWZhdWx0IgpyZWdpb249IlJlZ2lvbk9uZSIK
export OPENSTACK_CLOUD_CACERT_B64=Cg==
export OPENSTACK_DNS_NAMESERVERS=168.126.63.1
export OPENSTACK_FAILURE_DOMAIN=nova
export OPENSTACK_CONTROL_PLANE_MACHINE_FLAVOR=m1.medium
export OPENSTACK_NODE_MACHINE_FLAVOR=m1.medium
export OPENSTACK_IMAGE_NAME=ubuntu-2004-kube-v1.23.3
export OPENSTACK_SSH_KEY_NAME=sunmi
export OPENSTACK_EXTERNAL_NETWORK_ID=public

clusterctl generate cluter k3s-os-cluster --config ./cluster.yaml --infrastructure=openstack --kubernetes-version v1.23.3 --control-plane-machine-count=1 --worker-machine-count=1 > ./k3s-os-cluster.yaml



clusterctl generate cluster k3s-os-cluster --bootstrap k3s --infrastructure openstack --kubernetes-version v1.23.3 > ./k3s-os-cluster.yaml