apiVersion: v1
data:
  cacert: Cg==
  clouds.yaml: Y2xvdWRzOgogIG9wZW5zdGFjazoKICAgIGF1dGg6CiAgICAgIGF1dGhfdXJsOiBodHRwOi8vMTkyLjE2OC44OC4xMTo1MDAwL3YzLwogICAgICB1c2VybmFtZTogImVkZ2VjcmFmdCIKICAgICAgcGFzc3dvcmQ6ICJQYXNzMDAwMEAiCiAgICAgIHByb2plY3RfaWQ6IDNiNjZiNjlhOGQyNDQxNzA4ZDE3NzNjN2NmNDlkZTI1CiAgICAgIHByb2plY3RfbmFtZTogImVkZ2VjcmFmdC10ZXN0IgogICAgICB1c2VyX2RvbWFpbl9uYW1lOiAiRGVmYXVsdCIKICAgIHJlZ2lvbl9uYW1lOiAiUmVnaW9uT25lIgogICAgaW50ZXJmYWNlOiAicHVibGljIgogICAgaWRlbnRpdHlfYXBpX3ZlcnNpb246IDM=
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: os-mk8s-pure-cloud-config
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: os-mk8s-pure
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.96.0.1/12
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: MicroK8sControlPlane
    name: os-mk8s-pure-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
    kind: OpenStackCluster
    name: os-mk8s-pure
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackCluster
metadata:
  name: os-mk8s-pure
  namespace: default
spec:
  allowAllInClusterTraffic: true
  apiServerLoadBalancer:
    enabled: false
  cloudName: openstack
  dnsNameservers:
  - 168.126.63.1
  externalNetworkId: public
  identityRef:
    kind: Secret
    name: os-mk8s-pure-cloud-config
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: MicroK8sControlPlane
metadata:
  name: os-mk8s-pure-control-plane
  namespace: default
spec:
  controlPlaneConfig:
    initConfiguration:
      addons:
      - dns
      - ingress
  machineTemplate:
    infrastructureTemplate:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
      kind: OpenStackMachineTemplate
      name: os-mk8s-pure-control-plane
  replicas: 1
  version: v1.23.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: os-mk8s-pure-control-plane
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: m1.medium
      identityRef:
        kind: Secret
        name: os-mk8s-pure-cloud-config
      image: Ubuntu2004-Official
      sshKeyName: hostacloud
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: os-mk8s-pure-md-0
  namespace: default
spec:
  clusterName: os-mk8s-pure
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: MicroK8sConfigTemplate
          name: os-mk8s-pure-md-0
      clusterName: os-mk8s-pure
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
        kind: OpenStackMachineTemplate
        name: os-mk8s-pure-md-0
      version: v1.23.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: os-mk8s-pure-md-0
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: m1.medium
      identityRef:
        kind: Secret
        name: os-mk8s-pure-cloud-config
      image: Ubuntu2004-Official
      sshKeyName: hostacloud
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: MicroK8sConfigTemplate
metadata:
  name: os-mk8s-pure-md-0
  namespace: default
spec:
  template:
    spec: {}
